### PR TITLE
bump mammoth to 1.4.9 to hopefully fix lodash vulnerability

### PR DESCRIPTION
**Pull request by pschoffer**
Related to #138

### CODE REVIEW

**Comment by oussamaelkhalifi** [comment]
Still waiting for this to be merged

**Comment by lanechr** [comment]
Also waiting for this to be merged

**Comment by elallouette** [comment]
Any news on why is this still not merged please ?

**Comment by sonofole** [comment]
Please merge this, it is causing multiple security vulnerabilities.

**Comment by AlexandrDobrovolskiy** [comment]
Same, please merge

**Review by RealDrewKlayman — APPROVED** [review]
Fixes Bug

**Review by grindenrightnow — APPROVED** [review]

**Comment by mvoloskov** [comment]
Please merge this

**Comment by mattburlage** [comment]
bump

**Comment by mvoloskov** [comment]
I checked and it really fixes the problem. Please, merge this.

**Comment by pschoffer** [comment]
Closing as this probably won't merge ever :)

**Pull request closed without merging**
